(6-2)中級 従業員曖昧検索
takamasa-like-curry/ex-emp-management-bugfix pull request #14
Opened 2023-02-20 07:51 UTC by takamasa-like-curry

従業員一覧画面に曖昧検索機能を追加しました。

「AdministratorController」内の「fuzzySerch()」メソッドにて操作を行い空文字検索・該当なしについては「showList」メソッドに投げて、該当ありのみメソッド内で処理をしています。
動作確認ではエラー等はでていませんが、このような処理で問題ないでしょうか？
もし全ての条件においてメソッド内で処理の方が良ければ対応いたします。

確認お願いします。
問題なければマージお願いします。

2023-02-20 07:59 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-02-20 07:59 UTC, igamasayuki commented on src/main/java/com/example/service/EmployeeService.java
> +		}
この部分は削除で問題ありません。
複数件返すメソッドで、検索結果が存在しない場合は、０件のリストを返すことが一般的です。

2023-02-20 07:59 UTC, igamasayuki commented on src/main/java/com/example/repository/EmployeeRepository.java
> +		findByFuzzyNameSql.append(" WHERE name LIKE :fuzzySerchName;");
適切な項目で並び替えをお願いします。

2023-02-20 08:16 UTC, takamasa-like-curry commented
レビュー頂いた箇所について修正を行いました。
確認をお願いします。

2023-02-21 02:07 UTC, igamasayuki approved these changes
takamasa-like-curry

2023-02-21 02:07 UTC, merged