(5-3)上級 パスワード暗号化orハッシュ化
takamasa-like-curry/ex-emp-management-bugfix pull request #15
Opened 2023-02-21 03:23 UTC by takamasa-like-curry

管理者登録の際のパスワードのハッシュ化を行いました。
確認をお願いします。

問題なければマージお願いします。

2023-02-21 07:09 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-02-21 07:09 UTC, igamasayuki commented on src/main/java/com/example/common/InstanceEncoder.java
> +}
WebSecurityConfigクラスで以下の処理をしているためこのクラスは不要です。

以下はDIコンテナにBCryptPasswordEncoderを登録する記述のため１箇所に書けば問題ありません。

```
	@Bean
	PasswordEncoder passwordEncoder() {
		return new BCryptPasswordEncoder();
	}
```

2023-02-21 07:09 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +		administrator.setPassword(hashPasswod);
この処理はサービスクラスに書きましょう。業務処理のため。

2023-02-21 08:10 UTC, takamasa-like-curry commented
レビュー頂いた箇所を修正しました。
確認お願いします。

2023-02-22 07:05 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2023-02-22 07:05 UTC, merged